#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : iniparse
Version  : 0.4
Release  : 8
URL      : https://pypi.python.org/packages/source/i/iniparse/iniparse-0.4.tar.gz
Source0  : https://pypi.python.org/packages/source/i/iniparse/iniparse-0.4.tar.gz
Summary  : Accessing and Modifying INI files
Group    : Development/Tools
License  : MIT Python-2.0
Requires: iniparse-python
Requires: iniparse-data
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
iniparse is an INI parser for Python which is API compatible
with the standard library's ConfigParser, preserves structure of INI
files (order of sections & options, indentation, comments, and blank
lines are preserved when data is updated), and is more convenient to
use.

%package data
Summary: data components for the iniparse package.
Group: Data

%description data
data components for the iniparse package.


%package python
Summary: python components for the iniparse package.
Group: Default

%description python
python components for the iniparse package.


%prep
%setup -q -n iniparse-0.4

%build
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
python runtests.py
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/doc/iniparse-0.4/Changelog
/usr/share/doc/iniparse-0.4/LICENSE
/usr/share/doc/iniparse-0.4/LICENSE-PSF
/usr/share/doc/iniparse-0.4/README
/usr/share/doc/iniparse-0.4/index.html
/usr/share/doc/iniparse-0.4/style.css

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
